#!/bin/sh

set -e

MQTT=$(which mosquitto_pub)
TOPIC=sensors/qgp

[ -n "$MQTTUSER" ] || { echo "export MQTT username as MQTTUSER" >&2 ; exit 1 ; }
[ -n "$MQTTPASS" ] || { echo "export MQTT password as MQTTPASS" >&2 ; exit 1 ; }
[ -n "$MQTTHOST" ] || { echo "export MQTT server as MQTTHOST" >&2 ; exit 1 ; }

# swallow errors so we don't exit. no arguments.
mqttflush() {
  "$MQTT" --id qgp -h "$MQTTHOST" -t "$TOPIC" -m "{$POST}" -u "$MQTTUSER" -P "$MQTTPASS" || \
    { echo "error publishing to mqtt: $POST" >&2 ; }
}

# arguments: topic (key), message.
mqtt() {
  if [ -z "$POST" ] ; then
    POST="\"$1\":$2"
  else
    POST="$POST, \"$1\":$2"
  fi
}

# prints bytes RX from a /proc/net/dev line provided as $*
procnetdevrx() {
  echo $* | sed -e 's/ *//' | cut -d\  -f2
}

# prints bytes TX from a /proc/net/dev line provided as $*
procnetdevtx() {
  echo $* | sed -e 's/ *//' | cut -d\  -f10
}

stripnum() {
  echo "$@" | tr -d -c .[:digit:]-
}

if [ -z "$AMDGPU" ] ; then
  AMDGPU=$(sensors | grep ^amdgpu-pci) || echo "Couldn't find AMD GPU" >&2
fi

while true ; do
  POST=""

  # it seems HFLOW can change when USB devices are added or removed,
  # so go ahead and run the search each time =\ maybe only on failure?
  HFLOW=$(sensors | grep ^highflownext-hid) || echo "Couldn't find Aquacomputer highflow NEXT" >&2
  COOLTEMP=$(sensors -j | jq .\"$HFLOW\".\"Coolant\ temp\".temp1_input) 2> /dev/null
  if [ "$COOLTEMP" != "null" ] ; then
    mqtt aquacool $COOLTEMP
  fi
  FLOW=$(sensors -j | jq .\"$HFLOW\".\"Flow\ \[dL/h\]\".fan1_input) 2> /dev/null
  if [ "$FLOW" != "null" ] ; then
    # convert deciliters-per-hour to liters-per-minute
    FLOW=$(jq -n $FLOW/60/10)
    mqtt aquaflow $FLOW
  fi
  V5USB=$(sensors -j | jq .\"$HFLOW\".\"+5V\ USB\ voltage\".in1_input) 2> /dev/null
  if [ "$V5USB" != "null" ] ; then
    mqtt v5usb $V5USB
  fi

  UPSEC=$(cut -d\  -f1 < /proc/uptime)
  mqtt uptimesec $UPSEC

  # load average
  LOAD=$(cut -d\  -f1 < /proc/loadavg)
  mqtt loadavg $LOAD

  TCTL=$(sensors -j | jq '."k10temp-pci-00c3".Tctl[]') 2> /dev/null
  mqtt tctl $TCTL

  GPU=$(sensors -j | jq .\"$AMDGPU\".edge[]) 2> /dev/null
  mqtt gputemp $GPU

  reportfan() {
    VAL=$(echo $1 | cut -d. -f1)
    [ $VAL != "null" ] && [ $VAL -le 0 ] || mqtt $2 $VAL
  }

  XTOP0RPM=$(sensors -j | jq '."it8689-isa-0a40".fan1.fan1_input') 2> /dev/null
  reportfan $XTOP0RPM cpu0rpm

  FAN1RPM=$(sensors -j | jq '."it8689-isa-0a40".fan2.fan2_input') 2> /dev/null
  reportfan $FAN1RPM fan1

  MORARPM=$(sensors -j | jq '."it8689-isa-0a40".fan3.fan3_input') 2> /dev/null
  reportfan $MORARPM morarpm

  FAN2RPM=$(sensors -j | jq '."it8689-isa-0a40".fan4.fan4_input') 2> /dev/null
  reportfan $FAN2RPM fan2

  XTOP1RPM=$(sensors -j | jq '."it8689-isa-0a40".fan5.fan5_input') 2> /dev/null
  reportfan $XTOP1RPM cpu1rpm

  # network
  for i in r8169 r8152 sfc9120a sfc9120b ; do
    if STATS=$(grep $i: /proc/net/dev) ; then
      if [ -n "$STATS" ] ; then
        RX=$(procnetdevrx $STATS)
        TX=$(procnetdevtx $STATS)
        mqtt nicrxb$i $RX
        mqtt nictxb$i $TX
      fi
    fi
  done

  #MLX5TEMP=$(sensors -j | jq '.[]|select(.Adapter|test("Virtual device"))|.temp1.temp1_input') 2> /dev/null
  #mqtt nictempmlx5 $MLX5TEMP

  # SATA disks
  DISKTEMPS=$(sensors -j | jq '.[]|select(.Adapter|test("SCSI adapter"))|.temp1.temp1_input') 2> /dev/null
  DIDX=0
  for i in $DISKTEMPS ; do
    mqtt sata$DIDX $i
    DIDX=$((DIDX + 1))
  done

  # NVMe disks
  for i in /dev/nvme? ; do
    # text looks like: "temperature				: 50°C (323 Kelvin)"
    # in some error cases, a negative value is returned; elide these
    TEMP=$(nvme smart-log $i | grep ^temperature | cut -d\( -f1 | tr -d -c .[:digit:]-)
    S=$(echo $i | cut -d/ -f3)
    if [ "$TEMP" -ge 0 ] ; then
      mqtt "$S"temp $TEMP
    fi
  done

  # fs availability
  for i in / /home /media/qwop /media/qwopino ; do
    AVAIL=$(df $i --output=avail | sed -e 1d)
    AVAIL=$(stripnum $AVAIL)
    TOTAL=$(df $i --output=size | sed -e 1d)
    TOTAL=$(stripnum $TOTAL)
    PCENT=`jq -n \(1-$AVAIL/$TOTAL\)*100`
    NAME="fs`basename $i | sed -e 's/\//root/'`"
    mqtt "$NAME" $PCENT
  done

  if [ $((ITER % 100)) = 0 ] ; then
    HARTSFIELD=$(weather-util -m 30308 | grep Temperature: | cut -d\  -f5 || true)
  fi
  if [ -z "$HARTSFIELD" ] ; then
    HARTSFIELD=$(weather-util -m 30308 | grep Temperature: | cut -d\  -f5 || true)
  fi
  if [ -n "$HARTSFIELD" ] ; then
    mqtt hartsfield $HARTSFIELD
  fi

  SYSTEMDFAILED=$(systemctl --failed --output=json | jq length -)
  mqtt systemdfails $SYSTEMDFAILED

  mqttflush
  sleep 15
done
