#!/bin/sh

set -e

MQTT=$(which mosquitto_pub)
TOPIC=sensors/killermike

[ -n "$MQTTUSER" ] || { echo "export MQTT username as MQTTUSER" >&2 ; exit 1 ; }
[ -n "$MQTTPASS" ] || { echo "export MQTT password as MQTTPASS" >&2 ; exit 1 ; }
[ -n "$MQTTHOST" ] || { echo "export MQTT server as MQTTHOST" >&2 ; exit 1 ; }

# swallow errors so we don't exit. no arguments.
mqttflush() {
  "$MQTT" --id killermike -h "$MQTTHOST" -t "$TOPIC" -m "{$POST}" -u "$MQTTUSER" -P "$MQTTPASS" || \
    { echo "error publishing to mqtt: $POST" >&2 ; }
}

# arguments: topic (key), message.
mqtt() {
  if [ -z "$POST" ] ; then
    POST="\"$1\":$2"
  else
    POST="$POST, \"$1\":$2"
  fi
}

stripnum() {
    echo "$@" | tr -d -c .[:digit:]-
}

# prints bytes RX from a /proc/net/dev line provided as $*
procnetdevrx() {
  echo $* | sed -e 's/ *//' | cut -d\  -f2
}

# prints bytes TX from a /proc/net/dev line provided as $*
procnetdevtx() {
  echo $* | sed -e 's/ *//' | cut -d\  -f10
}

# this isn't going to change over our run
#mqtt kernelver "\"`uname -r`\""

CHIPID=nct6798-isa-0290

while true ; do
  POST=""
  # this moves around; find it dynamically
  if [ -z "$AMDGPU" ] ; then
    AMDGPU=$(sensors | grep ^amdgpu-pci) || echo "Couldn't find AMD GPU" >&2
  fi

  # SMBus nct6798-isa-0290 SuperIO
  for i in `seq 1 7` ; do
    FAN=$(sensors -j | jq .\"$CHIPID\".\"fan${i}\".fan${i}_input) 2> /dev/null
    mqtt fan$i $FAN
  done

  # k10 temp sensors. TCtl is offset for a "consistent fan policy across
  # all AMD Ryzen processors", i.e. as input to a fan management scheme.
  TCTL=$(sensors -j | jq '."k10temp-pci-00c3".Tctl[]') 2> /dev/null
  mqtt tctl $TCTL

  GPU=$(sensors -j | jq .\"$AMDGPU\".edge[]) 2> /dev/null
  mqtt gputemp $GPU

  # network
  for i in r8152 r8169 ; do
    STATS=$(cat /proc/net/dev | grep $i:) # FIXME continue on error
    if [ -n "$STATS" ] ; then
      RX=$(procnetdevrx $STATS)
      TX=$(procnetdevtx $STATS)
      mqtt nicrxb$i $RX
      mqtt nictxb$i $TX
    fi
  done

  # SATA disks
  DISKTEMPS=$(sensors -j | jq '.[]|select(.Adapter|test("SCSI adapter"))|.temp1.temp1_input') 2> /dev/null
  DIDX=0
  for i in $DISKTEMPS ; do
    mqtt sata$DIDX $i
    DIDX=$((DIDX + 1))
  done

  # fs availability
  for i in / /home /media/store ; do
    AVAIL=$(df $i --output=avail | sed -e 1d)
    AVAIL=$(stripnum $AVAIL)
    TOTAL=$(df $i --output=size | sed -e 1d)
    TOTAL=$(stripnum $TOTAL)
    PCENT=`jq -n \(1-$AVAIL/$TOTAL\)*100`
    NAME="fs`basename $i | sed -e 's/\//root/'`"
    mqtt "$NAME" $PCENT
  done

  UPSEC=$(cut -d\  -f1 < /proc/uptime)
  mqtt uptimesec $UPSEC

  # load average
  LOAD=$(cut -d\  -f1 < /proc/loadavg)
  mqtt loadavg $LOAD

  mqttflush
  sleep 15
done
