#!/bin/sh

# read the CPM data from an Arduino USB serial link, and update an RRD

set -e

usage() { echo "usage: $(basename $0) device rrdfile" ; }

[ $# -eq 2 ] || { usage >&2 ; return 1 ; }

DEV="$1"
RRD="$2"

rrdtool info "$RRD" > /dev/null || \
 { echo "$RRD wasn't an RRD, exiting" >&2 ; usage >&2 ; return 1 ; }

echo "reading disintegration counts from $DEV..."

# FIXME loop if $DEV doesn't exist, but not busily...
# can socat handle this for us?

COUNT=0

BAUD=115200

stty -F "$DEV" raw $BAUD -echo
socat - OPEN:"$DEV",B$BAUD | \
while read line ; do
  CPM="$(echo $line | cut -d\  -f1)"
  rrdupdate "$RRD" N:"$CPM"
  COUNT=$((COUNT + 1))
done

echo "processed $COUNT events"
