#!/bin/sh

set -e

usage() { echo "usage: $(basename $0) rrdfile output" ; }

[ $# -eq 2 ] || { usage >&2 ; return 1 ; }

RRD="$1"
GRAPH="$2"

rrdtool graphv "$GRAPH" -w 800 -h 600 -t "Disintegrations per minute"  -a PNG DEF:cpm=$RRD:geigercounts:AVERAGE LINE1:cpm#00ff00:"disintegrations"
