#!/bin/sh

set -e

MQTT=$(which mosquitto_pub)
TOPIC=mora3

[ -n "$MQTTUSER" ] || { echo "export MQTT username as MQTTUSER" >&2 ; exit 1 ; }
[ -n "$MQTTPASS" ] || { echo "export MQTT password as MQTTPASS" >&2 ; exit 1 ; }

stty 115200 -F /dev/tty-geiger

# we read thirty samples before publishing (this ought be 15s). we sum over
# the geiger counts, and average the mic samples.
G=0
M=0
MSAMPS=0
SAMPLES=0
exec cat < /dev/tty-geiger | while read line
do
  # all reported values are integers or floats with a mantissa of 0
  VAL=$(echo "$line" | cut -d\  -f2 | cut -d. -f1 | tr -d [:space:])
  if echo "$line" | grep '^Count: ' > /dev/null ; then
    G=$((G + VAL)) || { echo "Invalid geiger report: $VAL" >&2 ; }
  elif echo "$line" | grep '^Mic: ' > /dev/null ; then
    { M=$((M + VAL)) && MSAMPS=$((MSAMPS + 1)) ; } || { echo "Invalid mic report: $VAL" >&2 ; }
  fi
  SAMPLES=$((SAMPLES + 1))
  if [ $SAMPLES -ge 30 ] ; then
    "$MQTT" -u "$MQTTUSER" -P "$MQTTPASS" -t "$TOPIC" -m "{\"geiger\":\"$G\"}"
    VAL=$(echo "$M / $MSAMPS" | bc)
    "$MQTT" -u "$MQTTUSER" -P "$MQTTPASS" -t "$TOPIC" -m "{\"mic\":\"$VAL\"}"
    G=0
    M=0
    MSAMPS=0
    SAMPLES=0
  fi
done
