#!/bin/sh

set -e

MQTT=$(which mosquitto_pub)

[ -n "$MQTTUSER" ] || { echo "export MQTT username as MQTTUSER" >&2 ; exit 1 ; }
[ -n "$MQTTPASS" ] || { echo "export MQTT password as MQTTPASS" >&2 ; exit 1 ; }

# FIXME we need the device to be put in the correct mode, as done by e.g.
#  arduino-cli, before this will work. i think we can do so with stty?
exec cat < /dev/tty-geiger | while read line
do
  VAL=$(echo "$line" | cut -d\  -f2 | tr -d [:space:])
  if echo "$line" | grep '^Count: ' > /dev/null ; then
    TOPIC=geiger
  elif echo "$line" | grep '^Mic: ' > /dev/null ; then
    TOPIC=mic
  fi
  "$MQTT" -u "$MQTTUSER" -P "$MQTTPASS" -t "$TOPIC" -m "$VAL"
done
