#!/bin/sh

set -e

MQTT=$(which mosquitto_pub)
TOPIC=sensors

[ -n "$MQTTUSER" ] || { echo "export MQTT username as MQTTUSER" >&2 ; exit 1 ; }
[ -n "$MQTTPASS" ] || { echo "export MQTT password as MQTTPASS" >&2 ; exit 1 ; }

# arguments: topic (key), message. swallow errors so we don't exit.
mqtt() {
  "$MQTT" -t "$TOPIC/$1" -m "{\"$1\":$2}" -u "$MQTTUSER" -P "$MQTTPASS" || \
    { echo "error publishing to mqtt" >&2 ; }
}

while true ; do
  # these require root, ugh--set powercap-info suid root, or something similar =\.
  UPSW=$(pwrstat -status | grep Load | cut -d\  -f2 || echo "")
  if [ -n "$UPSW" ] ; then
    mqtt upswatts $UPSW
  else
    echo "couldn't read UPS power" >&2
  fi

  # we get our delay from this turbostat invocation
  TURBS=$(turbostat --quiet --Summary --hide idle,IRQ sleep 10 2>&1 | sed -n 3p)
  # we get Avg_MHz	Busy%	Bzy_MHz	TSC_MHz	IPC	CorWatt	PkgWatt
  AVGKHZ=$(echo $TURBS | cut -d\  -f1)
  AVGKHZ=$((AVGKHZ * 1000))
  BPCENT=$(echo $TURBS | cut -d\  -f2)
  BKHZ=$(echo $TURBS | cut -d\  -f3)
  BKHZ=$((BKHZ * 1000))
  PWATTS=$(echo $TURBS | cut -d\  -f7)
  mqtt pkgwatts $PWATTS
  mqtt cpuavgkhz $AVGKHZ
  mqtt cpubzykhz $BKHZ
  mqtt cpubpcent $BPCENT

done
