#!/bin/sh

set -e

MQTT=$(which mosquitto_pub)
TOPIC=sensors/schwarzgerät

[ -n "$MQTTUSER" ] || { echo "export MQTT username as MQTTUSER" >&2 ; exit 1 ; }
[ -n "$MQTTPASS" ] || { echo "export MQTT password as MQTTPASS" >&2 ; exit 1 ; }

# swallow errors so we don't exit. no arguments.
mqttflush() {
  "$MQTT" --id schwarzgerät -t "$TOPIC" -m "{$POST}" -u "$MQTTUSER" -P "$MQTTPASS" || \
    { echo "error publishing to mqtt: $POST" >&2 ; }
}

# arguments: topic (key), message.
mqtt() {
  if [ -z "$POST" ] ; then
    POST="\"$1\":$2"
  else
    POST="$POST, \"$1\":$2"
  fi
}

isnumber() {
  case "$1" in
    ''|*[!0-9]*) return 1 ; ;;
    *) return 0
  esac
}

while true ; do
  POST=""
  # these require root, ugh--set powercap-info suid root, or something similar =\.
  UPSW=$(pwrstat -status | grep Load | cut -d\  -f2 || echo "")
  if [ -n "$UPSW" ] ; then
    mqtt upswatts $UPSW
  else
    echo "couldn't read UPS power" >&2
  fi

  UPSV=$(pwrstat -status | grep Utility\ Voltage | cut -d\  -f3 || echo "")
  if [ -n "$UPSV" ] ; then
    mqtt Voltage $UPSV
  else
    echo "couldn't read UPS voltage" >&2
  fi

  # we get our delay from this turbostat invocation
  TURBS=$(turbostat --quiet --Summary --hide idle,IRQ sleep 10 2>&1 | tail -n 1)
  # we get Avg_MHz	Busy%	Bzy_MHz	TSC_MHz	IPC	CorWatt	PkgWatt
  BPCENT=$(echo $TURBS | cut -d\  -f2)
  if isnumber "$BPCENT" ; then
    mqtt cpubpcent $BPCENT
  fi
  PWATTS=$(echo $TURBS | cut -d\  -f7)
  if isnumber "$PWATTS" ; then
    mqtt pkgwatts $PWATTS
  fi
  AVGKHZ=$(echo $TURBS | cut -d\  -f1)
  BKHZ=$(echo $TURBS | cut -d\  -f3)
  # we can only do arithmetic ops if the operand is a number,
  # so test for that. this works in POSIX sh.
  if isnumber "$AVGKHZ" ; then
    if isnumber "$BKHZ" ; then
      AVGKHZ=$((AVGKHZ * 1000))
      BKHZ=$((BKHZ * 1000))
      mqtt cpuavgkhz $AVGKHZ
      mqtt cpubzykhz $BKHZ
    fi
  fi

  mqttflush
  sleep 15

done
