#!/bin/sh

set -e

MQTT=$(which mosquitto_pub)
TOPIC=sensors

[ -n "$MQTTUSER" ] || { echo "export MQTT username as MQTTUSER" >&2 ; exit 1 ; }
[ -n "$MQTTPASS" ] || { echo "export MQTT password as MQTTPASS" >&2 ; exit 1 ; }

# arguments: topic (key), message. swallow errors so we don't exit.
mqtt() {
  "$MQTT" -t "$TOPIC/$1" -m "{\"$1\":$2}" -u "$MQTTUSER" -P "$MQTTPASS" || \
    { echo "error publishing to mqtt" >&2 ; }
}

while true ; do
  # these require root, ugh--set powercap-info suid root, or something similar =\.
  UPSW=$(pwrstat -status | grep Load | cut -d\  -f2 || echo "")
  if [ -n "$UPSW" ] ; then
    mqtt upswatts $UPSW
  else
    echo "couldn't read UPS power" >&2
  fi

  # we get our delay from this turbostat invocation
  #turbostat --quiet --Summary --hide idle,IRQ sleep 10 2>&1 > /home/dank/turbocrappy
  #TURBS=$(tail -n 1 < /home/dank/turbocrappy)
  TURBS=$(turbostat --quiet --Summary --hide idle,IRQ sleep 10 2>&1 | tail -n 1)
  # we get Avg_MHz	Busy%	Bzy_MHz	TSC_MHz	IPC	CorWatt	PkgWatt
  BPCENT=$(echo $TURBS | cut -d\  -f2)
  mqtt cpubpcent $BPCENT
  PWATTS=$(echo $TURBS | cut -d\  -f7)
  mqtt pkgwatts $PWATTS
  AVGKHZ=$(echo $TURBS | cut -d\  -f1)
  BKHZ=$(echo $TURBS | cut -d\  -f3)
  # we can only do arithmetic ops if the operand is a number,
  # so test for that. this works in POSIX sh.
  case "$AVGKHZ" in
    ''|*[!0-9]*) echo "not a number: $AVGKHZ" ;;
    *) case "$BKHZ" in
         ''|*[!0-9]*) echo "not a number: $BKHZ" ;;
         *)
          AVGKHZ=$((AVGKHZ * 1000))
          BKHZ=$((BKHZ * 1000))
          mqtt cpuavgkhz $AVGKHZ
          mqtt cpubzykhz $BKHZ
         ;;
       esac ;;
  esac

done
